### ISSUE TITLE
missing files

### ISSUE THREAD

**Issue by pengzhangzhi** [LBM-EPFL/PeSTo#9]
Hi,
 the following files are missed in this repo. 
training_exclusion_lists = [ # "data/lists/ppdb5_set.txt", # "data/lists/masif-site_test_set.txt", # "data/lists/skempi_v2.txt", # "data/lists/memcplxdb.txt", # "data/lists/excluded.txt" ]
would you like to upload them?
Best,
Zhangzhi

**Comment by rubenalv** [comment]
If it helps, some of them were defined in the paper of MaSIF (https://github.com/LPDI-EPFL/masif). I did not use them so I did not dig for them, otherwise I would give you a better pointer.
